site_name: 'Buddhist Digital Resource Center Asset Manager'
site_description: 'Project documentation and User Manual for Asset Manager'
site_author: 'Jim Katz'

theme: readthedocs

nav:
- Home: index.md
- Requirements: req/requirements.md
- Building:
    - Design: design/design.md
- Resources:
  - About: resources/about.md
  - References: resources/resources.md

extra_css:
    - css/style.css
    - css/tooltip.css

extra:
  logo: images/bdrc-white.png
