site_name: 'Buddhist Digital Resource Center Asset Manager'
site_description: 'Project documentation and User Manual for Asset Manager'
site_author: 'Jim Katz'

theme: cinder

nav:
- Home: 'index.md'
- Building:
    - About: 'design/about.md'
    - Design: 'design/design.md'
- Resources: 'resources.md'

extra_css:
    - css/style.css
    - css/tooltip.css

extra:
  logo: images/bdrc-white.png
